analysis/ehrql/dataset_definition_ehrql_example.py
analysis/os_reports/codelists.py

This branch includes a simplified way to combine codelists for medications and creates combined codelists for long term conditions and community nursing.

Create combined codelists

---

analysis/os_reports/01_eol_service_report_charts.R
analysis/os_reports/02_eol_service_report.Rmd
project.yaml

added cause of death charts for each service.

Cause of death pull request

---

analysis/os_reports/dataset_definition_os_reports.py

Added '28' and '2B' to definition of emergency admissions.

Updated emadm definition

---

analysis/os_reports/01_eol_service_report_charts.R
analysis/os_reports/02_eol_service_report.Rmd
analysis/os_reports/dataset_definition_os_reports.py
project.yaml

This is new code for the addition of community nursing contacts to WP1 for the extension of the time series report. It is new ehrQL coding, so when we chat to Andrea next week I want to make sure it's doing what I think it is.

Os reports comuunity nursing

---

analysis/os_reports/01_eol_service_report_charts.R
analysis/os_reports/02_eol_service_report.Rmd
project.yaml

I have added a new cdv file to the reports and charts doc to count the number of people with at least one emergency admission by month and place of death. I have also updated the YAML file with the wildcard coding (*) to reduce the number of outputs listed.

Adding wildcard coding to YAML file and adding new CSV file to reports to show emadm per person

---

analysis/os_reports/01_eol_service_report_charts.R
project.yaml

Since the latest update to the R image, this project has had trouble running. In investigations, the place where it would hang was always on `write_csv` - this function comes from the `readr` package, which has been upgraded.  Replacing it with either the base `write.csv` or `fwrite` from the `data.table` package fixes the issue.  `fwrite` should be faster for large datasets.

Use fwrite function from data.table package instead of readr's write_csv

---

analysis/os_reports/01_eol_service_report_charts.R
project.yaml

Adapting CSV file code so that unrounded and rounded proportions can be viewed

Creating rounded and unrounded proportion CSV files 

---

analysis/os_reports/03_eol_WP2_quality_indicators.R
analysis/os_reports/codelists.py
analysis/os_reports/dataset_definition_os_reports.py
codelists/codelists.json
codelists/codelists.txt
codelists/user-sophie_julian-specialist-palliative-care.csv
project.yaml

updated code lists to include the specialist code lists . Added to the data set definition to include specialist palliative care. The R code shows proportion of people who dies that had specialist palliative care on their GP records 90 days before death. This includes rounding code and unrounded code (not for release). Proportion is given monthly and quarterly.

Specialist palliative care code

---

analysis/os_reports/01_eol_service_Descriptives_csvs.R
analysis/os_reports/02_eol_service_Descriptive_outputs.R
analysis/os_reports/dataset_definition_os_reports.py

Study quarters adjusted to start in March 2019, as registered deaths data starts in Feb 2019. 
Adjusted start of data collection period to Dec 2018 to allow for collection of historical use of hospital services.

Adjusting study quarters

---

analysis/os_reports/03_eol_WP2_quality_indicators.R
project.yaml

the dummy data makes it quite hard to see if this code is achieving what we want...?

breakdown of palliative care code proportion by place of death for cancer deaths 

---

analysis/os_reports/03_eol_WP2_quality_indicators.R
analysis/os_reports/07_eol_WP3_MAIHDA.R
project.yaml

Amending filter statement for specialist and palliative care data cuts for patients with cancer. 
Amending file labelling.

Editing  palliative care cancer data cuts and addressing smaller data edits required. 

---

analysis/os_reports/dataset_definition_os_reports.py

Adjusting to under 50's, and then 10-year age-bands.
Note added to highlight r.e. IMD that 1 = most deprived and 5 = least deprived.

Adjusting age-bands for MAIHDA analysis

---

analysis/os_reports/07_eol_WP3_MAIHDA.R
analysis/os_reports/dataset_definition_os_reports.py
project.yaml

Ethnicity groupings amended so that where ethnicity is not present in primary care data, it is supplemented with information from hospital records.

Amending ethnicity groupings 

---

analysis/os_reports/07_eol_WP3_MAIHDA.R
analysis/os_reports/dataset_definition_os_reports.py

Ethnicity from GP data supplemented with sus data where ethnicity would otherwise be missing.

Amending calculation of ethnicity in the dataset definition

---

analysis/os_reports/dataset_definition_os_reports.py

Testing an approach to identify missing values

Further revisions to ethnicity coding

---

analysis/os_reports/dataset_definition_os_reports.py

In order to filter by attendance status, change from opa_diag to opa.

Outpatient data change

---

analysis/os_reports/07_eol_WP3_MAIHDA.R
analysis/os_reports/dataset_definition_os_reports.py
project.yaml

Refining the df for the MAIHDA analysis and testing group sizes.

Maihda stage1 development

---

analysis/deaths-at-home-covid19/study_definition.py
analysis/deaths-at-home-covid19/study_definition_practice_measures.py
analysis/ehrql/dataset_definition_ehrql_example.py
analysis/os_reports/09_eol_Ethnicity_breakdown.R
analysis/os_reports/Legacy_files/study_definition_os_reports.py
analysis/os_reports/dataset_definition_os_reports.py
project.yaml

commented out gp interactions so this analysis could be run through level 4, changes were made to 6 files:
- commented out in 2 from previous study (deaths at home covid-19) in the study definition files.
-  commented out in ehrql dataset definition 
- commented out in old study definition 
- commented out in current dataset definition and project yaml for files which use gp interactions. 
MD code for actual analysis is in r script file 09.

Ethnicity analysis into main

---

analysis/os_reports/Legacy_files/MAIHDA analysis.R

- MAIHDA analysis file relating to GP interactions moved to legacy folder as OpenSAFELY could not support library packages required to run this analysis.

Restructuring MAIHDA files within folders.

---

analysis/os_reports/07_eol_WP3_MAIHDA.R
analysis/os_reports/dataset_definition_os_reports.py
project.yaml

These amendments remove the 'hashed' GP interactions code and set-up the MAIHDA analysis code to consider GP interactions as the outcome variable.

Merging MAIHDA Branch

---

analysis/os_reports/06_WP3_Binomial_MAIHDA_A&E_GP.R
analysis/os_reports/07_eol_WP3_MAIHDA_GP.R
project.yaml

- Adjusting GP analysis to run as a poisson model
- Adjusting A&E outputs to report model summary

A&E & GP outcome measure_MAIHDA revisions
